### ISSUE TITLE
Uygulama ismi düzenlenmeli

### ISSUE THREAD

**Issue by MertKocak** [MertKocak/zoo#5]

**Comment by muhammetaydinn** [comment]
ayrıca seo chat gpt ile zenginleştirilebilir.
yapay zeka ile de icon güncellenebilir.
yatay thumbnail güncellenebilir.

**Comment by muhammetaydinn** [comment]
Title: Animal Sounds - Listen to realistic animal sounds of lions, elephants, birds and more!

Description: Want to learn about different animal sounds? Look no further than Animal Sounds, the ultimate animal soundboard app for Android! With a wide variety of realistic animal sounds, from lions and elephants to birds and more, this app is perfect for kids and animal lovers of all ages. Explore different habitats and listen to the unique sounds each animal makes. Plus, the app includes a fun quiz mode to test your knowledge of animal sounds. Download Animal Sounds now and discover the world of animal sounds at your fingertips!

Keywords: animal sounds, soundboard, animal noises, animal calls, animal facts, animal quiz, animal habitat

Tags: animal sounds, animal, soundboard, animal noises, animal calls, animal facts, animal quiz, animal habitat

Note: it would be good to use these keywords in the app's screenshots and video preview as well.

This text should give a good idea of what the app is about, and uses keywords that are relevant to the app's content and features. The title, description, and tags should be optimized to include the keywords and make it clear what the app is about. Keep in mind that these are just example, you should tailor your own text according to your app features and target audience.

**Comment by muhammetaydinn** [comment]
"Explore the sounds of the animal kingdom with our intuitive and engaging animal sound app. From roaring lions to chirping birds, our app features a wide range of animal sounds to discover and enjoy. With high-quality audio recordings and visually striking images of each animal, our app is the perfect tool for animal lovers of all ages. Whether you're looking to learn more about the animals of the world or simply want to be entertained, our app has something for everyone. Download now and start your animal sound journey today!"

**Comment by muhammetaydinn** [comment]
Uygulama ikonunu için güncelleme atmam lazımmış

**Comment by muhammetaydinn** [comment]
"Animalound"
"Animaloundz"
"Sound Safari"
"The Animal Soundboard"
"Animalound World"
"Nature Soundz"
"Animalound Paradise"
"Wild Soundz"
"Soundz of Nature"
"The Animal Sound Experience" hayvan sesleri vs

**Comment by muhammetaydinn** [comment]
her dile özgü tasarım vs paylaşılabiliyormuş Şimdilik o yüzden görsellerde metin kullanmamaya çalışalım ama başlıklar ve açıklamalar her dil için eklenebilir.

**Comment by muhammetaydinn** [comment]
10dan fazla dile çeviri yaptım ceo denendi
ikon ve thumbnail değişicek ikon için güncelleme gelicek

**Comment by muhammetaydinn** [comment]
Seçilebilecek ikonlar

![sdaasdfasd_animal_sounds_app_icon_of_animal_sound_app_basic_car_992c7cfa-385c-45a4-9ee0-00e58ae43481](https://user-images.githubusercontent.com/72871376/213975887-903c0267-ead8-4c42-ae90-b448688d478f.png)

![sdaasdfasd_animal_sounds_app_icon_of_animal_sound_app_basic_car_26299929-a7af-41bd-8273-3f8202f43daa](https://user-images.githubusercontent.com/72871376/213975911-bbe245d5-b92f-4817-a543-8345677fe91b.png)


![maydin_animal_sound_app_graphic_desgin_app_gridview_animal_pict_1554e06e-7fe5-4acd-a72b-36ce56167226 (1)](https://user-images.githubusercontent.com/72871376/213976608-5a15637f-20dc-450b-a454-09d7c2ba686c.png)

![aasdasdwebp](https://user-images.githubusercontent.com/72871376/213976256-84029b6b-e706-47e2-a54d-8bbfe5665079.png)
![sdaasdfasd_app_icon_of_animal_sound_application_colorful_kid_ch_c9b5c21e-9eda-4ca0-93e1-fdcec3de10ea](https://user-images.githubusercontent.com/72871376/213976670-375a3a9b-1b0b-4ddb-a094-5215337c9629.png)


![unnamed](https://user-images.githubusercontent.com/72871376/213976116-0d383efc-b51f-4a3f-ae3d-bd324caf05ec.png)
